name: Build linux (ubuntu)

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest

    steps:
      - uses: actions/checkout@v2

      - name: cmake
        run: mkdir build && cd build && cmake ..
      - name: make bomberman
        run: make -C build bomberman
      - name: Archive binary
        uses: actions/upload-artifact@v1
        with:
          name: bomberman
          path: build/bomberman
