name: Generate documentation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt update --yes && sudo apt upgrade --yes && sudo apt install doxygen --yes
      - name: Run Doxygen
        run: cd $GITHUB_WORKSPACE && doxygen Doxyfile